/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ukk_spp;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LENOVO THINKPAD
 */
public class form_pembayaran extends javax.swing.JFrame {
    Connection con;
    DefaultTableModel tm;
    String idpembayaran;
    
    public void connect() {
        con = null;
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://127.0.0.1/db_spp", "root", "");
        } catch (Exception e) {
            System.out.print("ERROR KUERI KE DATABSE:\n" + e + "\n\n");
        }
    }
    
    private void refreshTable() {
        tm = new DefaultTableModel (null, 
                new Object[] {"NO. ", "NAMA PETUGAS", "NISN", "NAMA SISWA", "TANGGAL", "BULAN", "TARIF SPP", "JUMLAH DIBAYAR"});
        jTable1.setModel (tm);
        jTable1.removeColumn(jTable1.getColumnModel().getColumn(0));
        tm.getDataVector().removeAllElements();
        try {
            PreparedStatement s = con.prepareStatement("SELECT pembayaran.id_pembayaran, petugas.nama_petugas, pembayaran.nisn, "
                    + "siswa.nama, pembayaran.tgl_bayar, pembayaran.bulan, spp.nominal, pembayaran.jumlah_bayar FROM pembayaran INNER JOIN "
                    + "siswa USING(nisn) INNER JOIN spp on siswa.id_spp = spp.id_spp inner join petugas on "
                    + "pembayaran.id_petugas = petugas.id_petugas");
            ResultSet r = s.executeQuery();
            while (r.next()) {
                Object[] data = {
                    r.getString(1),
                    r.getString(2),
                    r.getString(3),
                    r.getString(4),
                    r.getString(5),
                    r.getString(6),
                    r.getString(7),
                    r.getString(8)
                };
                tm.addRow(data);
            }
        } catch (Exception e) {
            System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
        }
    }

    public void cbidpetugas() {
        try {
            PreparedStatement s = con.prepareStatement("SELECT * from petugas WHERE level='admin' or level='petugas'");
            ResultSet r = s.executeQuery();
            while (r.next()) {
                cbnmpetugas.addItem(r.getString("nama_petugas"));
            }
        } catch (SQLException e) {
            }
        }
    public void cbnisn() {
        try {
            PreparedStatement s = con.prepareStatement("SELECT * from siswa");
            ResultSet r = s.executeQuery();
            while (r.next()) {
                cbnisn.addItem(r.getString("nisn"));
            }
        } catch (SQLException e) {
            }
        }
    public void nominal() {
        try {
            PreparedStatement s = con.prepareStatement("SELECT * from spp");
            ResultSet r = s.executeQuery();
            while (r.next()) {
                cbtarif.addItem(r.getString("nominal"));
            }
        } catch (SQLException e) {
            }
        }
    /**
     * Creates new form form_pembayaran
     */
    public form_pembayaran() {
        initComponents();
        connect();
        cbidpetugas();
        cbnisn();
        nominal();
        refreshTable();
        txtidpetugas.hide();
        txttarif.hide();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        txtjmlbyr = new javax.swing.JTextField();
        cbnmpetugas = new javax.swing.JComboBox<>();
        cbnisn = new javax.swing.JComboBox<>();
        tglbyr = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtidpetugas = new javax.swing.JTextField();
        txttarif = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtsiswa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbtarif = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        cbbulan = new javax.swing.JComboBox<>();
        cbbulancari = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("NAMA PETUGAS");

        jLabel4.setText("NSIN");

        jLabel5.setText("TANGGAL BAYAR");

        jLabel8.setText("TARIF SPP");

        jLabel9.setText("JUMLAH BAYAR");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/save.png"))); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logOut.png"))); // NOI18N
        jButton4.setText("EXIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        txtjmlbyr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjmlbyrActionPerformed(evt);
            }
        });

        cbnmpetugas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih nama petugas" }));
        cbnmpetugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnmpetugasActionPerformed(evt);
            }
        });
        cbnmpetugas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbnmpetugasKeyPressed(evt);
            }
        });

        cbnisn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih NISN" }));
        cbnisn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbnisnActionPerformed(evt);
            }
        });
        cbnisn.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cbnisnKeyPressed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 204, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("DATA PEMBAYARAN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search.png"))); // NOI18N
        jButton2.setText("SEARCH");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/edit.png"))); // NOI18N
        jButton3.setText("EDIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtidpetugas.setEditable(false);

        jLabel6.setText("NAMA SISWA");

        jLabel2.setText("CARI DENGAN NISN :");

        cbtarif.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Tarif" }));
        cbtarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbtarifActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        jButton5.setText("DELETE");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setText("BULAN");

        cbbulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        cbbulancari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addGap(86, 86, 86)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtsiswa, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbnisn, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbnmpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(82, 82, 82)
                        .addComponent(jLabel2)
                        .addGap(187, 187, 187)
                        .addComponent(jButton2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtidpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbtarif, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txttarif, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtjmlbyr, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(cbbulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(cbbulancari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(tglbyr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(37, 37, 37)
                        .addComponent(jButton3)
                        .addGap(47, 47, 47)
                        .addComponent(jButton5)
                        .addGap(38, 38, 38)
                        .addComponent(jButton4)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 823, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel2)
                    .addComponent(cbbulancari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(cbnmpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtidpetugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(tglbyr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbnisn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(cbbulan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtsiswa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(cbtarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txttarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtjmlbyr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton5))
                .addGap(29, 29, 29))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int i = jTable1.getSelectedRow();
        if (i == -1) {
            return;
        }
        String id_pembayaran = (String) tm.getValueAt(i, 0);
        idpembayaran=id_pembayaran;
        
        String id_petugas = (String) tm.getValueAt(i, 1);
        cbnmpetugas.setSelectedItem(id_petugas);
        
        String nisn = (String) tm.getValueAt (i, 2);
        cbnisn.setSelectedItem(nisn);
        
        String siswa = (String) tm.getValueAt (i, 3);
        txtsiswa.setText(siswa);
        
        String bulan_bayar = (String) tm.getValueAt (i, 5);
        cbbulan.setSelectedItem(bulan_bayar);
        
        String nominal = (String) tm.getValueAt (i, 6);
        cbtarif.setSelectedItem(nominal);
        
        String jumlah_bayar = (String) tm.getValueAt(i, 7);
        txtjmlbyr.setText(jumlah_bayar);
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String tampilTanggal="yyyy-MM-dd";
        SimpleDateFormat df=new SimpleDateFormat(tampilTanggal);
        String tanggal=String.valueOf(df.format(tglbyr.getDate()));
        
        if (cbnmpetugas.getSelectedItem().equals("") || cbnisn.getSelectedItem().equals("") || txtsiswa.getText().equals("") || 
                txttarif.getText().equals("") || txtjmlbyr.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Data harus terisi semua");
        } else {
        try {
            PreparedStatement ps = con.prepareStatement("INSERT INTO pembayaran VALUES (?,?,?,? ,?,?,?)");
            ps.setInt(1, 0);
            ps.setString(2, txtidpetugas.getText());
            ps.setString(3, cbnisn.getSelectedItem().toString());
            ps.setString(4, tanggal);
            ps.setString(5, cbbulan.getSelectedItem().toString());
            ps.setString(6, txttarif.getText());
            ps.setString(7,txtjmlbyr.getText());
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Data telah tersimpan");
            refreshTable();
            
        } catch (Exception e) {
            System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
        }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        login log=new login();
        log.show();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        tm = new DefaultTableModel(null, new Object[] {"NO.", "NAMA PETUGAS", "NISN", "NAMA SISWA", "TANGGAL", "BULAN", "TARIF SPP", "JUMLAH BAYAR"});
        jTable1.setModel(tm);
        jTable1.removeColumn(jTable1.getColumnModel().getColumn(0));
        tm.getDataVector().removeAllElements();
        try {
            PreparedStatement s = con.prepareStatement("SELECT  pembayaran.id_pembayaran, petugas.nama_petugas, pembayaran.nisn,"
                    + "siswa.nama, pembayaran.tgl_bayar, pembayaran.bulan, spp.nominal, pembayaran.jumlah_bayar FROM pembayaran INNER JOIN "
                    + "siswa USING(nisn) INNER JOIN spp on siswa.id_spp = spp.id_spp inner join petugas on "
                    + "pembayaran.id_petugas = petugas.id_petugas WHERE bulan LIKE '%" 
                    + cbbulancari.getSelectedItem().toString() + "%'");
            ResultSet r = s.executeQuery();
            while(r.next()){
                Object[] data={
                r.getString(1),
                r.getString(2),
                r.getString(3),
                r.getString(4),
                r.getString(5),
                r.getString(6),
                r.getString(7),
                r.getString(8)
                    
                };
                tm.addRow(data);
            }
        } catch (Exception e){
            System.out.print("ERROR KUERI KE DATABASE:\n" + e + "\n\n");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        String tampilTanggal="yyyy-MM-dd";
        SimpleDateFormat df=new SimpleDateFormat(tampilTanggal);
        String tanggal=String.valueOf(df.format(tglbyr.getDate()));
        
         if (cbnmpetugas.getSelectedItem().equals("")|| cbnisn.getSelectedItem().equals("")||txttarif.getText().equals("")||
                 txtjmlbyr.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this,"Data harus terisi semua");
        } else {
        try {
            PreparedStatement ps = con.prepareStatement("UPDATE pembayaran SET id_petugas=?, nisn=?, tgl_bayar=?, bulan=?" 
                    + "id_spp=?, jumlah_bayar=? WHERE id_pembayaran=?");
            ps.setString(1, txtidpetugas.getText());
            ps.setString(2, cbnisn.getSelectedItem().toString());
            ps.setString(3, tanggal);
            ps.setString(4, cbbulan.getSelectedItem().toString());
            ps.setString(5, txttarif.getText());
            ps.setString(6, txtjmlbyr.getText());
            ps.setString(7, idpembayaran);
            
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Data telah di update ");
            refreshTable();
            
        } catch (Exception e) {
            System.out.print("ERROR KUERI KE DATABASE:\n" + e + "n\n");
        }       
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cbnmpetugasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbnmpetugasKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbnmpetugasKeyPressed

    private void cbnisnKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cbnisnKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbnisnKeyPressed

    private void cbnmpetugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnmpetugasActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement s = con.prepareStatement("SELECT * from petugas WHERE nama_petugas='" + cbnmpetugas.getSelectedItem().toString() + "'");
            ResultSet r = s.executeQuery();
            while (r.next()) {
                txtidpetugas.setText(r.getString("id_petugas"));
            }
        } catch (SQLException e) {
            }
    }//GEN-LAST:event_cbnmpetugasActionPerformed

    private void cbnisnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbnisnActionPerformed
        // TODO add your handling code here:
          try {
            PreparedStatement s = con.prepareStatement("SELECT * FROM siswa WHERE nisn='"+ cbnisn.getSelectedItem().toString() + "'");
            ResultSet r = s.executeQuery();
            while (r.next()) {
                txtsiswa.setText(r.getString("nama"));
            }
        } catch (SQLException e) {
            }
    }//GEN-LAST:event_cbnisnActionPerformed

    private void txtjmlbyrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjmlbyrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtjmlbyrActionPerformed

    private void cbtarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbtarifActionPerformed
        // TODO add your handling code here:
        try {
            PreparedStatement s = con.prepareStatement("SELECT * FROM spp WHERE nominal='"+ cbtarif.getSelectedItem().toString() + "'");
            ResultSet r = s.executeQuery();
            while (r.next()) {
                txttarif.setText(r.getString("id_spp"));
                txtjmlbyr.setText(r.getString("nominal"));
            }
        } catch (SQLException e) {
            }
    }//GEN-LAST:event_cbtarifActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        int ok = JOptionPane.showConfirmDialog(null,"Anda Yakin Ingin Menghapus Data ini='" + txtsiswa.getText() + "'", ".:: Konfirmasi ::.", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            try {
                PreparedStatement ps = con.prepareStatement("DELETE FROM pembayaran WHERE id_pembayaran=?");
                ps.setString(1, idpembayaran);
                ps.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data telah di delete");
                refreshTable();
        } catch (Exception e) {
            System.out.print("ERROR KUERI KE DATABASE:\n" + e + "n\n");     
            }
        }
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(form_pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(form_pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(form_pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(form_pembayaran.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new form_pembayaran().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbbulan;
    private javax.swing.JComboBox<String> cbbulancari;
    private javax.swing.JComboBox<String> cbnisn;
    private javax.swing.JComboBox<String> cbnmpetugas;
    private javax.swing.JComboBox<String> cbtarif;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private com.toedter.calendar.JDateChooser tglbyr;
    private javax.swing.JTextField txtidpetugas;
    private javax.swing.JTextField txtjmlbyr;
    private javax.swing.JTextField txtsiswa;
    private javax.swing.JTextField txttarif;
    // End of variables declaration//GEN-END:variables
}
